services:
  
  timescaledb:
    build:
      context: ./timescale
    image: timescaledb
    container_name: timescaledb
    hostname: timescaledb
    ports:
      - 10010:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TIMESCALEDB_TELEMETRY: off