services:
  
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: timescaledb
    hostname: timescaledb
    ports:
      - 8888:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TIMESCALEDB_TELEMETRY: off
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql