name: worker-influxdb 

services:
  telegraf:
    image: telegraf
    container_name: telegraf
    extra_hosts:
        - "broker1=${CLUSTER}"
        - "broker2=${CLUSTER}"
        - "broker3=${CLUSTER}"
        - "schema_registry=${SCHEMA_REGISTRY}"
        - "influx=${INFLUX}"
    environment:
      INFLUX_URL: http://influx:8181
      SCHEMA_REGISTRY_URL: http://schema_registry:9095
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
