FROM apache/kafka:latest

WORKDIR /opt/jmx_exporter

RUN wget https://github.com/prometheus/jmx_exporter/releases/download/1.4.0/\
jmx_prometheus_javaagent-1.4.0.jar -O /opt/jmx_exporter/jmx_prometheus_javaagent.jar

COPY ./kafka-metrics.yml .

ENV KAFKA_OPTS="-javaagent:/opt/jmx_exporter/jmx_prometheus_javaagent.jar=9098:/opt/jmx_exporter/kafka-metrics.yml"