MSGS: list[str] = [
    "User login failed due to invalid credentials",
    "Database connection established successfully",
    "Data synchronization completed with warnings",
    "File upload failed: Unsupported file type",
    "Session timeout occurred for user ID 12345",
    "Error parsing JSON response from API",
    "User registration successful",
    "Password reset request received for user ID 67890",
    "Database connection closed",
    "Application started successfully",
    "Configuration file loaded successfully",
    "Invalid input detected in user form",
    "API request timed out after 30 seconds",
    "User session expired due to inactivity",
    "Error connecting to external service: Connection refused",
    "File download completed successfully",
    "User permissions updated",
    "Database schema migration completed",
    "Service unavailable: Retry after 5 minutes",
    "Authentication token expired",
    "User profile updated successfully",
    "Error processing payment: Insufficient funds",
    "File not found: /uploads/document.pdf",
    "Service started on port 8080",
    "User logout successful",
    "Error during file extraction: Corrupted archive",
    "Database query execution failed",
    "Application shutdown initiated",
    "Error sending email: SMTP server not responding",
    "User account locked due to multiple failed login attempts",
    "File permission denied: /var/www/uploads",
    "Service stopped unexpectedly",
    "Error reading configuration file: Missing required field",
    "User registration failed: Email already exists",
    "Database connection pool exhausted",
    "File upload exceeded maximum size limit",
    "Service restarted due to configuration change",
    "Error parsing XML response from API",
    "User session terminated by admin",
    "Database backup completed successfully",
    "Error during data import: Invalid format",
    "User authentication failed: Invalid credentials",
    "File write failed: Disk space full",
    "Service unavailable: Maintenance in progress",
    "Error processing request: Timeout occurred",
    "User profile picture updated successfully",
    "Database connection timeout",
    "Error during data export: Permission denied",
    "User password changed successfully",
    "File deletion failed: File not found",
    "Service started with default configuration",
    "Error during data synchronization: Network error",
    "User account suspended",
    "Database restore completed successfully",
    "Error during file compression: Unsupported format",
    "User session extended successfully",
    "Service stopped due to critical error",
    "Error during data migration: Insufficient disk space",
    "User permissions reset to default",
    "Database index rebuild completed",
    "Error during file upload: File size exceeds limit",
    "Service restarted due to memory leak",
    "User account deleted successfully",
    "Database optimization completed",
    "Error during file download: Network timeout",
    "User authentication successful",
    "Service unavailable: High server load",
    "Error during data synchronization: Authentication failed",
    "User session expired due to inactivity",
    "Database connection failed: Invalid credentials",
    "Error during file extraction: Unsupported format",
    "User profile updated with new information",
    "Service started with custom configuration",
    "Error during data import: Duplicate entry",
    "User password reset successfully",
    "Database query execution successful",
    "Error during file write: Permission denied",
    "User account created successfully",
    "Service stopped due to configuration change",
    "Error during data export: Disk space full",
    "User session terminated due to inactivity",
    "Database connection established with SSL",
    "Error during file compression: Permission denied",
    "User profile picture removed successfully",
    "Service started with default settings",
    "Error during data migration: Timeout occurred",
    "User permissions updated to admin",
    "Database index rebuild failed",
    "Error during file upload: Network timeout",
    "User account locked due to suspicious activity",
    "Service restarted due to high memory usage",
    "Error during data synchronization: Server not found",
    "User session extended due to activity",
    "Database restore completed with warnings",
    "Error during file compression: File not found",
    "User profile updated with new settings",
    "Service stopped due to system overload",
    "Error during data import: Missing parameter",
    "User account deleted due to policy violation",
    "Service unavailable: Server overload",
    "Error during data export: Permission denied",
    "User session terminated due to timeout",
    "Database connection failed: Authentication error",
    "Error during file extraction: Unsupported compression",
    "User profile picture removed due to policy",
    "Service started with default parameters",
    "Error during data migration: Invalid format",
    "User permissions updated to full access",
    "Database index rebuild failed due to error",
    "Error during file upload: Network timeout",
    "User account locked due to suspicious activity",
    "Service restarted due to configuration change",
    "Error during data synchronization: File not found",
    "User session extended due to admin action",
    "Database restore failed: Corrupted data",
    "Error during file compression: Permission denied",
    "User profile updated with new information",
    "Service stopped due to critical error"
]

CLSES: list[str] = [
    "java.lang.Object",
    "java.lang.String",
    "java.lang.Integer",
    "java.lang.Double",
    "java.lang.Boolean",
    "java.lang.Character",
    "java.lang.Float",
    "java.lang.Long",
    "java.lang.Short",
    "java.lang.Byte",
    "java.lang.Math",
    "java.lang.System",
    "java.lang.Thread",
    "java.lang.Exception",
    "java.lang.RuntimeException",
    "java.lang.NullPointerException",
    "java.util.ArrayList",
    "java.util.LinkedList",
    "java.util.HashMap",
    "java.util.TreeMap",
    "java.util.HashSet",
    "java.util.TreeSet",
    "java.util.Collections",
    "java.util.concurrent.ConcurrentHashMap",
    "java.util.concurrent.CopyOnWriteArrayList",
    "java.util.concurrent.CountDownLatch",
    "java.util.concurrent.Semaphore",
    "java.io.File",
    "java.io.InputStream",
    "java.io.OutputStream",
    "java.io.FileReader",
    "java.io.FileWriter",
    "java.net.URL",
    "java.net.HttpURLConnection",
    "javax.servlet.Servlet",
    "javax.servlet.http.HttpServlet",
    "javax.servlet.http.HttpServletRequest",
    "javax.servlet.http.HttpServletResponse",
    "org.springframework.boot.SpringApplication",
    "org.springframework.boot.autoconfigure.SpringBootApplication",
    "org.springframework.context.ApplicationContext",
    "org.springframework.context.annotation.Bean",
    "org.springframework.stereotype.Component",
    "org.springframework.stereotype.Service",
    "org.springframework.stereotype.Controller",
    "org.springframework.web.bind.annotation.RestController",
    "org.springframework.web.bind.annotation.RequestMapping",
    "org.springframework.web.bind.annotation.GetMapping",
    "org.springframework.web.bind.annotation.PostMapping",
    "org.springframework.web.bind.annotation.PathVariable",
    "org.springframework.web.bind.annotation.RequestParam",
    "org.springframework.web.bind.annotation.RequestBody",
    "org.springframework.web.servlet.config.annotation.WebMvcConfigurer",
    "org.springframework.boot.CommandLineRunner",
    "org.springframework.data.jpa.repository.JpaRepository",
    "org.springframework.data.repository.CrudRepository",
    "org.springframework.beans.factory.annotation.Autowired",
    "org.springframework.beans.factory.annotation.Value",
    "org.springframework.boot.context.properties.ConfigurationProperties",
    "org.springframework.boot.context.properties.EnableConfigurationProperties",
    "org.springframework.http.ResponseEntity",
    "org.springframework.http.HttpStatus",
    "org.slf4j.Logger",
    "org.slf4j.LoggerFactory",
    "org.apache.commons.lang3.StringUtils",
    "org.apache.commons.io.FileUtils",
    "org.apache.commons.collections4.CollectionUtils",
    "org.hibernate.Session",
    "org.hibernate.SessionFactory",
    "org.hibernate.Transaction",
    "org.modelmapper.ModelMapper",
    "com.fasterxml.jackson.databind.ObjectMapper",
    "com.fasterxml.jackson.core.JsonProcessingException",
    "javax.validation.Valid",
    "javax.validation.constraints.NotNull",
    "javax.validation.constraints.Size",
    "org.springframework.web.client.RestTemplate",
    "org.springframework.http.HttpHeaders",
    "org.springframework.http.MediaType",
    "org.springframework.scheduling.annotation.Async",
    "org.springframework.scheduling.annotation.EnableAsync"
]

THREADS: list[str] = [
    "main",
    "AWT-EventQueue-0",
    "Reference Handler",
    "Finalizer",
    "Signal Dispatcher",
    "DestroyJavaVM",
    "Monitor Ctrl-Break",
    "Thread-0",
    "Thread-1",
    "Thread-2",
    "Worker-1",
    "Worker-2",
    "Worker-3",
    "Timer-0",
    "Timer-1",
    "Timer-2",
    "AsyncTask-1",
    "AsyncTask-2",
    "AsyncTask-3",
    "AsyncTask-4",
    "Scheduler-1",
    "Scheduler-2",
    "Scheduler-3",
    "Executor-1",
    "Executor-2",
    "Executor-3",
    "Executor-4",
    "HttpClient-Thread-1",
    "HttpClient-Thread-2",
    "Pool-1-thread-1",
    "Pool-1-thread-2",
    "Pool-1-thread-3",
    "Pool-2-thread-1",
    "Pool-2-thread-2",
    "Spring-Task-1",
    "Spring-Task-2",
    "Spring-Task-3",
    "Cache-Refresher-1",
    "Cache-Refresher-2"
]


URLS: list[str] = [
    "https://app.example.com/",
    "https://app.example.com/about",
    "https://app.example.com/contact",
    "https://app.example.com/terms",
    "https://app.example.com/privacy",
    "https://app.example.com/status",
    "https://app.example.com/blog/archive",
    "https://app.example.com/login",
    "https://app.example.com/register",
    "https://app.example.com/logout",
    "https://app.example.com/password-reset",
    "https://app.example.com/verify-email",
    "https://app.example.com/dashboard",
    "https://app.example.com/dashboard/overview",
    "https://app.example.com/dashboard/settings",
    "https://app.example.com/dashboard/notifications",
    "https://app.example.com/dashboard/security",
    "https://app.example.com/products/new",
    "https://app.example.com/products/featured",
    "https://app.example.com/categories",
    "https://app.example.com/cart",
    "https://app.example.com/checkout",
    "https://app.example.com/orders",
    "https://app.example.com/orders/history",
    "https://app.example.com/billing",
    "https://app.example.com/invoices",
    "https://app.example.com/help",
    "https://app.example.com/faq",
    "https://app.example.com/docs",
    "https://app.example.com/docs/getting-started",
    "https://app.example.com/docs/api",
    "https://app.example.com/admin",
    "https://app.example.com/admin/users",
    "https://app.example.com/admin/roles",
    "https://app.example.com/admin/settings",
    "https://app.example.com/admin/logs",
    "https://api.example.com/v1/status",
    "https://api.example.com/v1/docs",
    "https://api.example.com/v1/health",
    "https://app.example.com/it/",
    "https://app.example.com/en/",
    "https://app.example.com/v2/",
    "https://app.example.com/users/rrbokmeiozojypickarzejyqzymkqf/settings",
    "https://app.example.com/users/zatcpomdkfrfwqggyyenavzvjczcck/settings",
    "https://app.example.com/users/lccuypvacstymzcfvxdfhlzgrgpczy/settings",
    "https://app.example.com/users/tbabrgtssnmrboanwegwkxffendgli/settings",
    "https://app.example.com/users/xesvhraghctwqkvkpmfcxddhbduxld/settings",
    "https://app.example.com/users/fcbcwvutchkmthayemsagkkmlkwkqm/orders",
    "https://app.example.com/users/uzzglrjjgkyxhblrgsgpvvaakkgqcv/orders",
    "https://app.example.com/users/fwotlhvsobpguoykwlqxyjbzpjugys/orders",
    "https://app.example.com/users/vyzlnojzwmnwubsvwydsocwbmtpynu/orders",
    "https://app.example.com/users/mbmhbwfyscvfmyuawafyruycjkcodp/orders",
    "https://app.example.com/users/bdsbdjzzlpnhilsccyuqypsinvegyc/wishlist",
    "https://app.example.com/users/vrmajgbuelxqqitcyvjmtcczpzobxv/wishlist",
    "https://app.example.com/users/kymykakzsagrhephrkpihlkfscxkuu/wishlist",
    "https://app.example.com/users/iawwslxrntfynnhzvvjndpiectyfio/wishlist",
    "https://app.example.com/users/fnjncowufhjuexzcnjhhusetycbngi/wishlist",
    "https://api.example.com/v1/users/nxduwnvvxlftpkmnlwwqlylvmpatej",
    "https://api.example.com/v1/users/rectldkumzkxqvwputgtinlwebjdga",
    "https://api.example.com/v1/users/ccnoxowcgunqjypjrudfkcsmbxlfbn",
    "https://api.example.com/v1/users/kmqdnuhseqrqmedrqfoqzzvnplisxj",
    "https://api.example.com/v1/users/nvcbdgmnyhgrlzqrzrhpaxewxqqlux",
    "https://app.example.com/orders/qmmbazddegkgoljippxcculwhijetx",
    "https://app.example.com/orders/vvlxrcpewhkswfkmbozjjmctjcypvi",
    "https://app.example.com/orders/sebsnlnmswshwktvcdbxzqyhqzmwsb",
    "https://app.example.com/orders/ecsypbmzgqvwddriajihbixkunferb",
    "https://app.example.com/orders/jukvxuydyfxcqjxdqyspymoczvbsxn",
    "https://app.example.com/orders/siolzbxfcvsyfumsfbtlyidrkltjtl/invoice",
    "https://app.example.com/orders/ydiemayihrxtkjwzdrruoujaiuvcxg/invoice",
    "https://app.example.com/orders/qdlvivajsjczimqfsswglwtfsqcton/invoice",
    "https://app.example.com/orders/udacedzxmzinxvbqyogkzylxskvzsn/invoice",
    "https://app.example.com/orders/kmgvyvwzzbmjqqskdvyocwfyobuwjn/invoice",
    "https://app.example.com/orders/xgljxldzwqacktxlgqacjsxpdlkbap/tracking",
    "https://app.example.com/orders/ilmtcisdtlbrijvnkzhfuydrzmzrxm/tracking",
    "https://app.example.com/orders/abarmwkmiqqwawypsolxtkrybhidzz/tracking",
    "https://app.example.com/orders/hmbadkwpguoeovhnmprxhoedxfcbyj/tracking",
    "https://app.example.com/orders/mdzuabhemmufzsgungxcbmohqugzsh/tracking",
    "https://api.example.com/v1/orders/qtwudoscavwwqyrfcqtswsyungvceh",
    "https://api.example.com/v1/orders/oevmhmgciusafxduaplnyztrcevfga",
    "https://api.example.com/v1/orders/rgvfvoansdgwuobtczcdanilzztbhv",
    "https://api.example.com/v1/orders/egbkrlknlyhxizeypokvhgenbgmdmh",
    "https://api.example.com/v1/orders/ginjjxfesmiatmmwwspivmagnzbvqd",
    "https://api.example.com/v1/categories/frvshigqfrpcunxjeswkcmrfixbahs",
    "https://api.example.com/v1/categories/ktvrzrqycyvwahtpnpwwxeqgvckvkj",
    "https://api.example.com/v1/categories/gzkpvfuopflhapmbuscsijjmydmorj",
    "https://api.example.com/v1/categories/bjxleilnglagrqqskbifnjcgboyxdl",
    "https://api.example.com/v1/categories/uzrxynfayvllbblypnrljhvnimasvc",
    "https://app.example.com/products/tglfdqdriklzngqfgwmlrbsghtgjta",
    "https://app.example.com/products/rdcrkioegpesecfqcjjqnpsjfpgbrr",
    "https://app.example.com/products/fhpafdfolzsbskrqefkbpbdzxuzbiq",
    "https://app.example.com/products/bosutfcskpuzkmkanrgwmiyardeqqz",
    "https://app.example.com/products/esmduekdcvaxsohanadspgmpoumypo",
    "https://api.example.com/v1/products/pncsdplvwiiunvcatjlfluwxtwnwxw",
    "https://api.example.com/v1/products/lksjcywpgcjftmlxjqgomdbhezkssp",
    "https://api.example.com/v1/products/ojslzmbfphxzqsjjqnmwnatifgwuej",
    "https://api.example.com/v1/products/wrlacyvprlppapxaewrdcifmercryi",
    "https://api.example.com/v1/products/pbdjmqthqoizbnlddlumxiexstgizq",
    "https://app.example.com/blog/sreysdiaguhnumsqhbvpuathoevjfw",
    "https://app.example.com/blog/wwerymwsubugfuynrmyhdcpviaejcj",
    "https://app.example.com/blog/tcvpufymkrprycwugdzouyzxdybdef",
    "https://app.example.com/blog/yukugenwnsauxzfkbbuthpeospcqsf",
    "https://app.example.com/blog/tnacbjslhjqkczvoqwkhpowmtglbdq",
    "https://app.example.com/products/taudvlhnpwaotwwehsnultbmecbihq/",
    "https://app.example.com/products/jctvtadpisrlkjdjwqcrcuoqhqcotf/",
    "https://app.example.com/products/jivnbrtlqnmsvuikqcqqlegusbjpiq/",
    "https://app.example.com/products/blbyniblhwybvzlawenndpvzdjkfrf/",
    "https://app.example.com/products/bdpdtmjumpsqoemgpdjdimqnvjhgjh/",
    "https://app.example.com/dashboard/profile/vcratvkfqjbxnwxsdhntecqkpzutbx",
    "https://app.example.com/dashboard/profile/nfaqjgxjxqycgferwixpdoelgznlzv",
    "https://app.example.com/dashboard/profile/dnjolfvrnxhhtmgmnumbjqvjlaejyq",
    "https://app.example.com/dashboard/profile/ieikrvjfjyzfktujesbusbubbwewqw",
    "https://app.example.com/dashboard/profile/rvejvipbxyjanotzukodopflsczyou",
    "https://app.example.com/products/search/stlatrkhbkbpdiiakhlqyyfmmilskk",
    "https://app.example.com/products/search/zhlzjlgfebutkcvyxoesaveuaxqhyp",
    "https://app.example.com/products/search/uvzygaidifejrllqteqtefosyovdbc",
    "https://app.example.com/products/search/djdgytjfvvbfftbhvkbbzfheuullbt",
    "https://app.example.com/products/search/vmcamoclmaqljxmxiaghfynjtxhqfk",
    "https://app.example.com/blog/search/sqbslffnwwnvsxvfblwlfghrbeaiot",
    "https://app.example.com/blog/search/dmrhexckmtisunlkzisgayikcctvjb",
    "https://app.example.com/blog/search/feehafzfmpucxclynmoepsqppxwemm",
    "https://app.example.com/blog/search/bxexxgfchpeahfkbcybqiytfoavujw",
    "https://app.example.com/blog/search/fxzsrvaiosucabfevhhlzfhaftfrfc"
]

USERS: list[str] = [
    "andrea.rossi",
    "lucia.bianchi",
    "mario.verdi",
    "federica.gallo",
    "giovanni.martini",
    "alessia.rinaldi",
    "francesco.neri",
    "simone.fabbri",
    "martina.mancini",
    "valentina.moretti",
    "stefano.marini",
    "elena.gatti",
    "giulia.pellegrini",
    "davide.ferrari",
    "ilaria.benedetti",
    "riccardo.santoro",
    "chiara.morini",
    "matteo.russo",
    "veronica.costa",
    "gabriele.santoro",
    "claudia.romani",
    "lorenzo.menini",
    "paola.giovanni",
    "nicola.damiani",
    "eleonora.santini",
    "filippo.rossini",
    "sara.deangelo",
    "alberto.morini",
    "beatrice.lombardi",
    "enzo.torri",
    "francesca.santoro",
    "marco.lenzi",
    "cristina.berti",
    "stefano.conti",
    "elisa.mazzoni",
    "fabio.rinaldi",
    "maria.fabbri",
    "daniele.parisi",
    "sabrina.morelli",
    "marco.galli",
    "laura.martinelli",
    "giovanni.cerulli",
    "francesca.giordano",
    "luca.rinaldi",
    "valeria.sartori",
    "andrea.lombardo",
    "chiara.fabbri",
    "giacomo.venturi",
    "martina.costa",
    "federico.rossi",
    "elena.monti",
    "stefano.ferrari",
    "giulia.russo",
    "matteo.marini",
    "ilaria.pellegrini",
    "daniele.mancini",
    "veronica.gallo",
    "marco.damiani",
    "paola.mazzoni",
    "francesco.berti",
    "sara.menini",
    "nicola.conti",
    "claudia.torri",
    "luca.santoro",
    "beatrice.ferrara",
    "enzo.russo",
    "eleonora.venturi",
    "filippo.lombardo",
    "sabrina.rossi",
    "alberto.giordano",
    "giulia.parisi",
    "fabio.costa",
    "maria.gallo",
    "giovanni.mazzoni",
    "francesca.moretti",
    "luca.giordano",
    "chiara.sartori",
    "giacomo.rossi",
    "martina.berti",
    "federico.venturi",
    "elena.torri",
    "stefano.lombardi",
    "giulia.monti",
    "matteo.ferrara",
    "ilaria.cerulli",
    "daniele.lenzi",
    "valeria.fabbri",
    "marco.giordano",
    "paola.santoro",
    "francesco.rinaldi",
    "sara.venturi",
    "nicola.ferrari",
    "claudia.costa",
    "andrea.gallo",
    "chiara.martini",
    "giacomo.monti",
    "martina.fabbri",
    "federico.mazzoni",
    "elena.rossi",
    "stefano.giordano",
    "giulia.damiani",
    "matteo.lombardi",
    "ilaria.parisi",
    "daniele.torri",
    "veronica.lenzi",
    "marco.ferrara",
    "paola.russo",
    None
]

STATUS_CODES: list[int] = [
    200,   
    301,  
    302,  
    400, 
    401,  
    403,  
    404,  
    500,  
    503   
]

USER_AGENTS: list[str] = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.6613.120 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.6613.120 Safari/537.36",
    "Mozilla/5.0 (Linux; Android 15; Pixel 8 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.6613.120 Mobile Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 13.5; rv:129.0) Gecko/20100101 Firefox/129.0",
    "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0",
    "Mozilla/5.0 (Android 14; Mobile; rv:128.0) Gecko/128.0 Firefox/128.0",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 13_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15",
    "Mozilla/5.0 (iPhone; CPU iPhone OS 17_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Mobile/15E148 Safari/604.1",
    "Mozilla/5.0 (iPad; CPU OS 17_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Mobile/15E148 Safari/604.1",
    "Mozilla/5.0 (Windows NT 11.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Edg/128.0.2739.54 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.6613.120 Safari/537.36 Edg/128.0.2739.54",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.6613.120 Safari/537.36 OPR/114.0.5272.61",
    "Mozilla/5.0 (Linux; Android 14; SM-G996B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.6613.120 Mobile Safari/537.36 OPR/114.0.5272.61",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.6613.120 Safari/537.36 Brave/128.0.6613.120",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.6613.120 Safari/537.36 Brave/128.0.6613.120"
]

SEVERITY = [
    "INFO",
    "DEBUG",
    "WARNING",
    "ERROR"
]

METHODS = [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "HEAD",
    "CONNECT",
    "OPTIONS",
    "TRACE",
    "PATCH"
]