services:
  s3proxy:
    image: andrewgaul/s3proxy:latest
    container_name: s3proxy
    hostname: s3proxy
    environment:
      S3PROXY_ENDPOINT: http://0.0.0.0:8080
      S3PROXY_AUTHORIZATION: none
      JCLOUDS_PROVIDER: filesystem-nio2
      JCLOUDS_FILESYSTEM_BASEDIR: /data
    ports:
      - 10008:8080
    volumes:
      - ./s3-data:/data