services:
 schema-registry:
    image: confluentinc/cp-schema-registry:latest
    container_name: schema-registry
    ports:
      - 9095:8085
    extra_hosts:
      - "broker1=${CLUSTER}"
      - "broker2=${CLUSTER}"
      - "broker3=${CLUSTER}"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://broker1:9092,broker2:9093,broker3:9094
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8085
      SCHEMA_REGISTRY_HOST_NAME: ${HOST}
      SCHEMA_INTER_INSTANCE_PROTOCOL: http