networks:
  cluster-net:
    driver: bridge

x-broker-common-env: &common-env
  KAFKA_PROCESS_ROLES: broker,controller
  KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker1:9093,2@broker2:9093,3@broker3:9093
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
  KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
  KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  CLUSTER_ID: 8cQAdE44QTWV_0HLozHOOQ 
  KAFKA_LOG_DIRS: /opt/kafka/data
  KAFKA_BROKER_RACK: 1

services:
  broker1:
    build:
      context: ./broker
    image: broker-jmx
    hostname: broker1
    container_name: broker1
    environment:
      <<: *common-env
      KAFKA_NODE_ID: 1
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://broker1:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${HOST_ADDR}:9092
    ports:
      - 9092:9092
      - 9098:9098
    volumes:
      - ./topic-creation.sh:/opt/kafka/setup/topic-creation.sh
    networks:
      - cluster-net

  broker2:
    build:
      context: ./broker
    image: broker-jmx
    hostname: broker2
    container_name: broker2
    environment:
      <<: *common-env
      KAFKA_NODE_ID: 2
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://broker2:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${HOST_ADDR}:9093
    ports:
      - 9093:9092
      - 9099:9098

    networks:
      - cluster-net

  broker3:
    build:
      context: ./broker
    image: broker-jmx
    hostname: broker3
    container_name: broker3
    environment:
      <<: *common-env
      KAFKA_NODE_ID: 3
      KAFKA_BROKER_ID: 3
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://broker3:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${HOST_ADDR}:9094
    ports:
      - 9094:9092
      - 9100:9098
    networks:
      - cluster-net

  prometheus:
    build: 
      context: ./prometheus
    image: kafka-prometheus
    container_name: prometheus
    ports:
      - 9999:9090
    networks:
      - cluster-net